### ISSUE TITLE
Usage of pytest addopts with xdist

### ISSUE THREAD

**Issue by kasium** [reverbc/pylint-pytest#5]
Hi guys,
first of all, I really love this plugin.

I recently added "--dist loadfile" to the addopts's of pytest (used by pytest-xdist). Since then, the plugin doesn't work anymore. Any clue?

Best regards,
Kai

**Comment by reverbc** [comment]
Thanks for using the plugin and reporting the issue Kai!

After checking, it turns out to be this lazy hack where I invoke a pytest session to collect the names of fixtures: https://github.com/reverbc/pylint-pytest/blob/pylint-pytest-0.3.0/pylint_pytest/checkers/fixture.py#L74-L77

If a `pytest.ini` (or other equivalent configuration files) is present with `pytest-xdist` plugin + below config:
```ini
[pytest]
addopts = --dist loadfile
```
pytest will not be able to execute. We can view the stderr by invoking the command manually:
```bash
$ pytest --fixtures
================ test session starts ================
platform darwin -- Python 3.8.3, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /Users/reverbc/Workspace/pylint-pytest/sandbox, configfile: pytest.ini
plugins: xdist-2.2.1, forked-1.3.0
ERROR: MISSING test execution (tx) nodes: please specify --tx
```

This can be fixed by appending `--collect-only` to that lazy hack pytest invocation so that `pytest-xdist` will basically ignore `--dist loadfile` since we're collecting only and not going to distribute them into workers.

PR will be out in a few seconds.
